version: "4"
services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"     # for services to connect
      - "15672:15672"   # for web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
